calibration_dataset:
  name: coco
  num_classes: 90
  num_frames: 50
  path: ./dependencies/datasets/coco
  shuffle: true
  split: val2017
input_dataset:
  name: coco
  num_classes: 90
  num_frames: 5000
  path: ./dependencies/datasets/coco
  shuffle: false
  split: val2017
metric:
  label_offset_pred:
    -1: 0
    0: 1
    1: 2
    2: 3
    3: 4
    4: 5
    5: 6
    6: 7
    7: 8
    8: 9
    9: 10
    10: 11
    11: 12
    12: 13
    13: 14
    14: 15
    15: 16
    16: 17
    17: 18
    18: 19
    19: 20
    20: 21
    21: 22
    22: 23
    23: 24
    24: 25
    25: 26
    26: 27
    27: 28
    28: 29
    29: 30
    30: 31
    31: 32
    32: 33
    33: 34
    34: 35
    35: 36
    36: 37
    37: 38
    38: 39
    39: 40
    40: 41
    41: 42
    42: 43
    43: 44
    44: 45
    45: 46
    46: 47
    47: 48
    48: 49
    49: 50
    50: 51
    51: 52
    52: 53
    53: 54
    54: 55
    55: 56
    56: 57
    57: 58
    58: 59
    59: 60
    60: 61
    61: 62
    62: 63
    63: 64
    64: 65
    65: 66
    66: 67
    67: 68
    68: 69
    69: 70
    70: 71
    71: 72
    72: 73
    73: 74
    74: 75
    75: 76
    76: 77
    77: 78
    78: 79
    79: 80
    80: 81
    81: 82
    82: 83
    83: 84
    84: 85
    85: 86
    86: 87
    87: 88
    88: 89
    89: 90
    90: 91
  run_dir: /data/ssd/files/a0393608/work/code/ti/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/8bits/od-2020_tflitert_coco_tf1-models_ssdlite_mobiledet_dsp_320x320_coco_20200519_tflite
model_info:
  metric_reference:
    accuracy_ap[.5:.95]%: 28.9
postprocess:
  detection_thr: 0.3
  formatter:
    dst_indices:
    - 0
    - 1
    - 2
    - 3
    name: DetectionYXYX2XYXY
    src_indices:
    - 1
    - 0
    - 3
    - 2
  ignore_index: null
  normalized_detections: true
  resize_with_pad: false
  save_output: false
  shuffle_indices: null
  squeeze_axis: 0
preprocess:
  add_flip_image: false
  backend: cv2
  crop:
  - 320
  - 320
  data_layout: NHWC
  interpolation: null
  pad_color: 0
  resize:
  - 320
  - 320
  resize_with_pad: false
  reverse_channels: false
session:
  artifacts_folder: artifacts
  dir_tree_depth: 3
  extra_inputs: null
  input_data_layout: NHWC
  input_mean: null
  input_optimization: true
  input_scale: null
  input_shape: null
  model_file: /data/ssd/files/a0393608/work/code/ti/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/8bits/od-2020_tflitert_coco_tf1-models_ssdlite_mobiledet_dsp_320x320_coco_20200519_tflite/model/ssdlite_mobiledet_dsp_320x320_coco_20200519.tflite
  model_folder: model
  model_id: od-2020
  model_path: model/ssdlite_mobiledet_dsp_320x320_coco_20200519.tflite
  model_type: null
  num_inputs: 1
  num_tidl_subgraphs: 16
  output_shape: null
  run_dir: od-2020_tflitert_coco_tf1-models_ssdlite_mobiledet_dsp_320x320_coco_20200519_tflite
  runtime_options:
    accuracy_level: 1
    advanced_options:activation_clipping: 1
    advanced_options:add_data_convert_ops: 3
    advanced_options:bias_calibration: 1
    advanced_options:calibration_frames: 50
    advanced_options:calibration_iterations: 50
    advanced_options:channel_wise_quantization: 0
    advanced_options:high_resolution_optimization: 0
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:quantization_scale_type: 0
    advanced_options:weight_clipping: 1
    artifacts_folder: /data/ssd/files/a0393608/work/code/ti/edgeai-algo/edgeai-benchmark/work_dirs/modelartifacts/8bits/od-2020_tflitert_coco_tf1-models_ssdlite_mobiledet_dsp_320x320_coco_20200519_tflite/artifacts
    debug_level: 0
    import: 'no'
    object_detection:confidence_threshold: 0.3
    object_detection:nms_threshold: 0.45
    object_detection:top_k: 200
    platform: J7
    priority: 0
    tensor_bits: 8
    tidl_tools_path: /data/ssd/files/a0393608/work/code/ti/edgeai-algo/edgeai-benchmark/tidl_tools
    version: '8.2'
  session_name: tflitert
  supported_devices: null
  target_device: pc
  tensor_bits: 8
  tidl_offload: true
  tidl_tools_path: /data/ssd/files/a0393608/work/code/ti/edgeai-algo/edgeai-benchmark/tidl_tools
  work_dir: ./work_dirs/modelartifacts/8bits
task_type: detection
